- include/kernels/matx_conv_kernels.cuh
- include/kernels/matx_filter_kernels.cuh
- include/kernels/matx_utility_kernels.cuh
- include/matx_defines.h
- include/matx_half.h
- include/matx_half_complex.h
- include/matx_radar.h
- include/matx_random.h
- include/matx_reduce.h
- include/matx_scalar_ops.h
- include/matx_shape.h
- include/matx_signal.h
- include/matx_tensor.h
- include/matx_tensor_generators.h
- include/matx_tensor_ops.h
- include/matx_tensor_utils.h
- include/matx_type_utils.h
Host compilers don't recognize __host__/__device__ annotations. This change conditionally adds them in if coming from nvcc.
> Removing __host__ and __device__ qualifiers for host compilers

- include/matx_tensor.h
Before, we have to call `.Print(0)`, `.Print(0, 0)`, `.Print(0, 0, 0)` or `.Print(0, 0, 0, 0)` to print the whole tensor (except 0-D tensors), which is not friendly. In addition, the [01_introduction.ipynb](https://github.com/NVIDIA/MatX/blob/main/docs_input/notebooks/01_introduction.ipynb) says that we could call `.Print()` on tensors to print the whole tensor.
So I added an alias to `.Print(0)`, `.Print(0, 0)`, `.Print(0, 0, 0)` or `.Print(0, 0, 0, 0)` by introducing an overloaded template function`Print(Args... dims)` that will be instantiated only when the arguments are empty and the rank of the tensor is greater than 0. This alias function actually constructs the `0, 0, ..., 0` arguments list and passes it to the original `Print(Args... dims)`.
The new interface has been tested on …
> Added a Print() to print the whole tensor

- test/00_io/FileIOTests.cu
just a minor bug - I believe this is intended to be the second dimension here.
> Minor bugfix in FileIOTests.cu

- include/matx_allocator.h
- include/matx_storage.h
- include/matx_tensor.h
closes #121 
This is a partial fix for printing user-defined pointers. It's partial because another issue (#110) would maintain the user pointers across allocations, which it doesn't do right now. This will also only work for device pointers provided by a user (not host only). There is currently no way to identify what type of pointer this is, but since we're primarily a GPU library, this is a good temporary tradeoff. Note that it's important to also make sure you make the pointer `non_owning`  type as to not have MatX free the memory on destruction: 
```
cudaMalloc(&ptr, 100*4);
auto c = make_tensor<float, 1, non_owning>((float*)ptr, {100});
```
> Allow Print() for user-defined memory

- README.md
"A set of MatX notebooks" now directs users to the correct folder.
> Fix broken notebook link in Quick Start Guide

- include/matx_cub.h
- include/matx_reduce.h
- test/00_operators/ReductionTests.cu
2D inputs for summing and sorting were broken due to memory allocation issues.
Fixed #134
> Fixing CUB sorting for 2D inputs

- README.md
Fix the architecture selection example that lacked a `D` in `-DCMAKE_...`.
Also add some code-block syntax highlighting.
> [DOC] README: Fix Arch Flags, Formatting

- CMakeLists.txt
- include/matx_make.h
- include/matx_tensor.h
- test/00_tensor/BasicTensorTests.cu
> Throw an exception if using SetVals on non-managed pointer

- include/matx_tensor_ops.h
- test/00_operators/OperatorTests.cu
- test/00_tensor/ViewTests.cu
Includes a unit test that i used to reproduce my exact problem.
> Fix grid dimensions for transpose.

- CMakeLists.txt
There's a bug where downstream repositories using a newer version of `RAPIDS.cmake` will have it overridden by MatX on subsequent builds. This prevents MatX from downloading `RAPIDS.cmake` if it already exists.
> Download RAPIDS.cmake only if it does not exist.

- docs_input/api/tensorops.rst
- include/matx_set.h
- include/matx_tensor.h
- include/matx_tensor_ops.h
- include/matx_type_utils.h
- test/00_operators/OperatorTests.cu
This operator takes an operator/tensor
and an index array and logically gathers elements from that index array.
This allows the user to logically select/broadcast elements from a
dimension of the tensor.  This operator could then be stored in a memory
backed tensor to create a linear ordering of an operator to pass into a
library backed routine like matmul or fft.
> Implementing remap operator.

- docs_input/api/tensorops.rst
- include/matx_corr.h
- include/matx_tensor_ops.h
- test/00_operators/OperatorTests.cu
reverse/shift APIs now take a template parameter for the dims instead of having them in the function name.  They also can take multiple DIMs.  This is consistent with the remap APIs.  Fixes #206
> Update reverse/shift APIs

- include/matx_tensor_ops.h
- test/00_operators/OperatorTests.cu
This is a breaking change.  For consistency it is best to update this
sooner rather than later.
> Change sign of shift to match python/matlab.

- include/matx/transforms/cub.h
- include/matx/transforms/reduce.h
- test/00_operators/ReductionTests.cu
Also added uint64_t/int64_t atomics.
> Fixed sum() using wrong iterator type

- examples/simple_radar_pipeline.cu
Performance calculation isn't taking into account the number of channels in the test.
> Fix calculation for pulses/channel/sec

- docs_input/quickstart.rst
As title says, fix of two typos in documentation
> Fix typos in documentation

- examples/CMakeLists.txt
- examples/conv2d.cu
- include/matx/kernels/conv.cuh
- include/matx/transforms/conv.h
- test/00_transform/ConvCorr.cu
This version is functionally correct.  Supports all batching options, switching signal and filter, operators, etc.
Performance optimized version will come later.
> Convolution overhaul.

- include/matx/core/tensor_utils.h
- include/matx/core/type_utils.h
- include/matx/operators/binary_operators.h
- include/matx/operators/ifelse.h
- include/matx/operators/index.h
- include/matx/operators/sign.h
1)  sign(x)  this returns -1 if negative, 0 if 0, and 1 if positive. 2)  index(dim) this returns the index of the tensor in the provided dim.
2) required some infastructure changes to support a rankless and sizeless operator.  I added a sentinal maxNoRank to signal this.
> Adding 2 new operators:

- bench/00_transform/qr.cu
- bench/CMakeLists.txt
- examples/CMakeLists.txt
- examples/qr.cu
- include/matx/operators/sign.h
- include/matx/transforms/qr.h
- include/matx/transforms/solver.h
- include/matx/transforms/transforms.h
- test/00_solver/QR2.cu
- test/CMakeLists.txt
Rename cusparse wrapper to cusparse_qr.
Cusolver API doesn't currently produce QR but instead R and the HH vectors.
> implement QR for small batched matrices.

- include/matx/core/iterator.h
- include/matx/transforms/cub.h
> Removing inheritance from std::iterator

- include/matx/core/tensor.h
- test/00_tensor/BasicTensorTests.cu
Allows local tensors to go out of scope and DLPack client owns them
> Adding ref-count for DLPack 

- include/matx/transforms/matmul.h
- test/00_transform/MatMul.cu
Currently, if a tensor contains 0-stride dimensions in one of the last two dimensions, then that tensor will not be used directly as input/output to cublas matmul and a copy will be made transparently. This generates copies during matvec operations because matvec clones a tensor and delegates to matmul, which then copies the tensor because the clone creates a 0-stride dimension. This change allows 0-stride dimensions if the dimension size is 1 (and thus no index will stride in that dimension) and thus eliminates allocations/frees and copies when calling matvec.
> Allow 0-stride dimensions for cublas input/output

- bench/00_operators/reduction.cu
- include/matx/core/iterator.h
- include/matx/core/tensor_utils.h
- include/matx/core/type_utils.h
- include/matx/operators/binary_operators.h
- include/matx/operators/index.h
- include/matx/operators/unary_operators.h
- include/matx/transforms/cub.h
- include/matx/transforms/reduce.h
- test/00_operators/ReductionTests.cu
- Added 16-bit support for several reduction types (both `__half` and `__nvbfloat16`
- Added unit tests for 16-bit reductions supported
- Added 16-bit support to `softmax`
- Added bias term on `softmax` to match Python's implementation
> 16-bit float reductions + updated softmax

- include/matx/transforms/matmul.h
cuBLASLt only needs a 4MB buffer currently as per the cuBLAS team.
> Reduced cuBLASLt workspace size

- include/matx/transforms/copy.h
- test/00_transform/Copy.cu
- test/CMakeLists.txt
Add a single argument version of copy() that allocates a new tensor of the same type/size as the tensor being copied and performs a deep copy into the new tensor.
> Add single argument copy() and copy() tests

- include/matx/operators/remap.h
- test/00_operators/OperatorTests.cu
Add remap() support for 0-rank index tensors
This update treats 0-rank index tensors as if they were rank-1 index tensors of size 1.
> Add rank0 tensor remap support

- include/matx/core/tensor.h
- include/matx/core/tensor_utils.h
- include/matx/executors/device.h
- test/00_operators/OperatorTests.cu
Attempting to build some code with newer versions of Clang highlighted a few issues, including a throw from a noexcept method, an assertion removing a function call in release builds, and some runtime rank-checks used in constexpr expressions.
> Fix a few issues highlighted by linters/clang

- CMakeLists.txt
- bench/CMakeLists.txt
- docs_input/notebooks/exercises/compile_and_run.sh
- examples/CMakeLists.txt
- test/CMakeLists.txt
> CMake fixes found by user

- CMakeLists.txt
- cmake/CheckPythonLibs.cmake
- include/matx/core/iterator.h
- include/matx/core/tensor_impl.h
- test/01_radar/ambgfun.cu
- test/CMakeLists.txt
Various fixes for CMake and default constructors for CUDA 12.3+. Thanks to @siegLoesch for the fixes on CMake
> Fixed cupy check for unit tests, default constructors, and file IO

- include/matx/core/pybind.h
- test/00_io/FileIOTests.cu
Modifies TensorViewToNumpy and NumpyToTensorView to accommodate rank=5 tensors.
> Modifies TensorViewToNumpy and NumpyToTensorView for rank = 5

- include/matx/core/pybind.h
- test/00_io/FileIOTests.cu
Fixes issue where complex types could not be used with NumpyToTensorView because conversion is required to go from `cuda::std::complex<T>` to/from `std::complex<T>`. 
- Added unit tests to verify that `NumpyToTensorView` and `TensorViewToNumpy` work with complex types.
> Latest NumpyToTensorView<T> function requires complex conversion for complex types

- include/matx/operators/remap.h
> Fixed unused variable warning

- docs_input/api/index.rst
- docs_input/api/resample_poly.rst
- include/matx/kernels/resample_poly.cuh
- include/matx/transforms/resample_poly.h
- include/matx/transforms/transforms.h
- test/00_transform/ResamplePoly.cu
- test/CMakeLists.txt
- test/test_vectors/generators/00_transforms.py
Initial version of a polyphase resampler. This version is focused primarily on correctness and a simple interface (i.e. no temporary work buffers).
> Adding initial polyphase resampler transform

- include/matx/kernels/conv.cuh
- include/matx/operators/cast.h
- include/matx/operators/clone.h
- include/matx/operators/fftshift.h
- include/matx/operators/flatten.h
- include/matx/operators/interleaved.h
- include/matx/operators/kronecker.h
- include/matx/operators/planar.h
- include/matx/operators/r2c.h
- include/matx/operators/repmat.h
- include/matx/operators/reshape.h
- include/matx/operators/reverse.h
- include/matx/operators/select.h
- include/matx/operators/self.h
- include/matx/operators/shift.h
- test/00_operators/OperatorTests.cu
> Added lvalue semantics to operators that needed it

- include/matx/core/tensor_utils.h
- include/matx/transforms/fft.h
- include/matx/transforms/solver.h
Closes #382 
@luitjens already added FFT support
> Added operator support to solver functions

- include/matx/operators/shift.h
Found Issues when broadcasting/having mixed size inputs to the `shift `operator. These changes:
- Adds additional runtime checks to the constructor of the operator to make sure both the input and shift operators are compatible with the desired output. 
- Fixed Rank function for situations where an input/shift operator may be broadcast during execution
- Fixed Size function for situations where an input/shift operator may be expanded during execution
> Added Protections for Shift Operator inputs and fixed issues with size/Shape returns for certain input sizes

- docs_input/api/logic/comparison/isclose.rst
- docs_input/api/logic/truth/allclose.rst
- examples/spectrogram.cu
- include/matx/operators/isclose.h
- include/matx/operators/operators.h
- include/matx/transforms/reduce.h
- test/00_operators/OperatorTests.cu
- test/00_operators/ReductionTests.cu
> Added isclose and allclose functions

- examples/CMakeLists.txt
- examples/channelize_poly_bench.cu
- examples/resample_poly_bench.cu
- include/matx/kernels/resample_poly.cuh
- include/matx/transforms/resample_poly.h
- test/00_operators/ReductionTests.cu
- test/00_transform/ResamplePoly.cu
Optimize resample_poly by using larger launch grids in cases with a small number of batches and/or a small upsampling factor. The new launch grids are particularly helpful for large signals without batches and low upsampling factors. Also add support for a wider range of operators via mapply.
> resample_poly optimizations and operator support

- include/matx/transforms/fft.h
The FFT plans currently use managed memory for their work area allocations. The associated memory prefetch calls cause issues in WSL2 (raised in https://github.com/NVIDIA/MatX/issues/153). The work areas are not exposed to users, so this PR changes the allocations to async device memory allocations.
> Use device mem instead of managed for fft workbuf

- include/matx/transforms/matmul.h
- test/00_transform/MatMul.cu
cuBLASLt allows a stride of 0 for A/B, which improves cache usage/loads for common matrices.
Closes #474
> Support stride 0 A/B batches for GEMMs

- bench/00_transform/conv.cu
Adds benchmarks for FFT vs direct convolution. Results on A100:
FFT convolution is not using a pre-computed filter and is computing the FFT each time
> Adding FFT convolution benchmarks

- examples/cmake_sample_project/CMakeLists.txt
- examples/cmake_sample_project/main.cu
updating print call to new version from old deprecated version.
> Fixing sample Cmake Project

- include/matx/operators/fft.h
- include/matx/operators/fftshift.h
- include/matx/operators/slice.h
- test/00_operators/OperatorTests.cu
Add PreRun methods for slice and fftshift operators. This allows the operators to be composed with transforms (e.g. fftshift1D(fft(x))).
> Add PreRun methods for slice/fftshift operators

- examples/simple_radar_pipeline.h
- include/matx/operators/base_operator.h
- include/matx/operators/fft.h
- include/matx/transforms/conv.h
- include/matx/transforms/fft.h
- test/00_transform/FFT.cu
Add explicit checking of the input/output tensor sizes for 1D FFTs. Throw an exception if the sizes are not as expected, even in Release builds. One consequence of the checks is that they enforce that zero padding applied within the fft() operator be explicit (via the fft_size) param rather than implicit.
> Add FFT1D tensor size checks

- examples/fft_conv.cu
- include/matx/operators/fft.h
FFT no longer implicitly zero-pads input signals, so pass the expected transform length explicitly.
> Add explicit FFT length to fft_conv example

- examples/resample_poly_bench.cu
- include/matx/kernels/resample_poly.cuh
- include/matx/transforms/resample_poly.h
- test/00_transform/ResamplePoly.cu
Add additional resample_poly kernels that are more optimal in specific cases (e.g., in the case of a pure downsampler). Currently,
there are three kernels, but only two of them are in use. There are some cases for which the third is fastest, but a pattern for when that will be the case is not yet clear.
> Optimize resample poly kernels

- include/matx/core/half.h
- include/matx/core/half_complex.h
Set copy ctor and copy assignment methods to default. Also use default ctors for both matxHalf and matxHalfComplex. Thus, the MatX half types no longer initialize to zero.
> Make matxHalf trivially copyable

- include/matx/core/tensor.h
- include/matx/operators/repmat.h
Removed old `MAX_TENSOR_DIM` variable and it's use in repmap to limit the rep_ vector. fixes issues with repmat > RANK 4
> removing old hardcoded limit for repmat rank size

- include/matx/transforms/solver.h
- test/00_solver/Cholesky.cu
- test/test_vectors/generators/00_solver.py
For contiguous input/output tensors, avoid creating a temporary tensor for use with cusolver. Also clear old batch pointers when populating new batch pointers prior to the factorization.
> Avoid async alloc in some Cholesky decomp cases

- include/matx/core/tensor.h
- include/matx/transforms/filter.h
- test/CMakeLists.txt
Versions of gcc prior to 9.3 have a bug parsing [[maybe_unused]] when applied to the first argument in a constructor:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81429
Although we do not officially support gcc versions prior to 9.3, this is a workaround for a couple such cases.
Also, switch from CMake COPY_FILE to COPY to maintain compatability with CMake 3.20 (COPY_FILE was added in 3.21)
> Workaround for maybe_unused parse bug in old gcc

- include/matx/operators/matvec.h
- test/00_transform/MatMul.cu
For matvecs, the batch dimensions for A and B should match and the final output dimension should match dim Rank-1 from A. Also generalize batching support so that the size of out_dims_ is based on the output rank.
> Fix matvec output dims to match A rather than B

- include/matx/transforms/cub.h
For some CUB reduction types, the batches field in the CUB params struct is uninitialized. The field is not needed for the reduction, but it is included when performing cache lookups, so the uninitialized value could cause false negatives (cache misses) and additional plan creations. This did not cause correctness issues but could impact performance. Thus, zero-initialize the batches field to prevent false negatives on cache lookup. The CUB cache is currently disabled by default but can be enabled at build time by the user.
> Zero-initialize batches field in CUB params

- .github/ISSUE_TEMPLATE/bug_report.md
A few modifications to make the Bug-report issue template better:
1. Capitalize the sub-titles.
2. Fix a typo (snippers -> snippets).
> Update Bug Report Issue Template

- include/matx/transforms/matmul.h
> Check matmul types and error at compile-time if the backend doesn't support them

- docs_input/api/manipulation/rearranging/transpose.rst
- include/matx/transforms/cov.h
- include/matx/transforms/matmul.h
- test/00_operators/OperatorTests.cu
- test/00_transform/Cov.cu
- test/test_vectors/generators/00_transforms.py
Fix a few issues with batched cov() transforms:
- Use transpose_matrix instead of transpose for the batched transposed deviations. Thus, dimensions [0, RANK-2) match the sizes of the batched dimensions from the non-transposed deviations.
- Use stream-oriented async allocators for temporaries and set the memory space to MATX_ASYNC_DEVICE_MEMORY.
- Make some changes in dimension-checking for batched matmul() transforms. Compute the number of batches using the dimensions of C and, if necessary, broadcast A or B into the batched dimensions.
- Add a cov() unit test case with batching and rectangular inputs.
One remaining issue is that we allocate 3-4 times the size of the input for temporary storage. This storage is part of a cached plan that currently is not evicted/freed, so if the …
> Fix batched cov transform

- include/matx/core/allocator.h
- include/matx/core/cache.h
- include/matx/core/pybind.h
- include/matx/core/tensor_utils.h
- include/matx/transforms/copy.h
- include/matx/transforms/cov.h
- include/matx/transforms/cub.h
- include/matx/transforms/fft.h
- include/matx/transforms/filter.h
- include/matx/transforms/inverse.h
- include/matx/transforms/matmul.h
- include/matx/transforms/solver.h
- test/00_tensor/BasicTensorTests.cu
Leaks in pybind are still reported, but are considered innocuous at this point since it's only in unit tests.
> Update caching for transforms to fixing all leaks reported by compute-sanitizer

- include/matx/core/utils.h
- include/matx/transforms/matmul.h
The recommended workspace size for Hopper+ is 32 MiB. Increasing the workspace size from 4 MiB to 32 MiB improves matmul performance for smaller matrices on H100.
> Increase cublas workspace to 32 MiB for Hopper+

- include/matx/transforms/matmul.h
1)  if beta!=0 copy C in.  2) detect additional case that cublas doesn't support.
> matmul bug fixes.  

- include/matx/core/tensor_utils.h
When printing operators there is a race condition between the copy and the print.  This patch adds synchronization to avoid that race condition.
> Added missing synchronization 

- include/matx/core/file_io.h
This PR maily improves File IO functions' doxygen comments:
- Added some missing arguments & return.
- Fixed some read/write verbs.
- `header` to `skip_header` for better readability.
I build and run FileIO tests and all tests passed.
> Refine some file I/O functions' doxygen comments

- docs_input/api/logic/truth/isinf.rst
- docs_input/api/logic/truth/isnan.rst
- include/matx/operators/scalar_ops.h
- include/matx/operators/unary_operators.h
- test/00_operators/OperatorTests.cu
Adds IsNan and IsInf operators that are useful for checking results.
Tests added to `OperatorFuncs`.
> Adds IsNan and IsInf Operators

- include/matx/transforms/qr.h
- include/matx/transforms/svd.h
Fixes #543
Previously QR and SVD could devide by zero in some situations.  New version avoids those divisions eliminating the nans.
Also reworked workspace APIs to make interface easier to use.
> Fix nans in QR and SVD.

- include/matx/core/nvtx.h
We need to change `#include <nvToolsExt.h>` into `#include <nvtx3/nvToolsExt.h>`.
The old form (`#include <nvToolsExt.h>`) requires linking to dynamic library (`libnvToolsExt.so`), while the new form is header-only. In PR #548, @cliffburdick changed CMakeLists.txt to make matx link to `CUDA::nvtx3` instead of `UDA::nvToolsExt` if CMake has a higher version that supports it. Thus if you use a CMake version >= 3.25, you will only use nvtx3 headers, without linking to `libnvToolsExt.so`. But we are still including the old `<nvToolsExt.h>`, rather than the newer `<nvtx3/nvToolsExt.h>`. For some functions, the old `<nvToolsExt.h>` don't contain implementations. This makes the linking fail with **undefined reference** errors.
For example, using CMake 3.28, I cannot build the `conv2d` target in …
> Fix NVTX3 include path

- CMakeLists.txt
On a first cmake run, when rapids-cmake-dir is not defined, we call add_subdirectory(cmake/rapids-cmake) to include the various rapids modules. On subsequent runs, rapids-cmake-dir is defined in the cache, so the path needs to be appended to the module path for the include directives. Currently, we modify CMAKE_PREFIX_PATH instead of CMAKE_MODULE_PATH.
> Add rapids-cmake-dir, if defined, to CMAKE_MODULE_PATH

- docs_input/api/math/misc/abs2.rst
- include/matx/operators/scalar_ops.h
- include/matx/operators/unary_operators.h
- test/00_operators/OperatorTests.cu
Add abs2() operator that is equivalent to abs()*abs() without the extra loads and the unnecessary sqrt operators associated with complex abs() calculations.
> Add abs2() operator for squared abs()

- include/matx/transforms/matmul.h
- test/00_transform/Cov.cu
- test/00_transform/MatMul.cu
When performing a matmul on two tensors with mismatched ranks, at least one of which is greater than 3, broadcast the lower-rank tensor. This also fixes a bug in the batched cov transform.
> Broadcast lower-rank tensors during batched matmul

- include/matx/transforms/fft.h
- test/00_transform/FFT.cu
- test/test_vectors/generators/00_transforms.py
- Fixes several issues where input/output, dimensions, or types were swapped in internal calculations.
- Adds tests for non-square, batched, strided batched, R2C, and C2R 2D transforms.
> Fix bugs in 2D FFTs and add tests

- include/matx/core/tensor_utils.h
Issue #606 correctly points out that use of a "print" macro can conflict with other libraries, such as Eigen.  This PR changes the print macro back to a matx::print function.
> Change print macro to matx namespaced function

- docs/_sources/api/creation/operators/ones.rst
- docs_input/api/creation/operators/zeros.rst
- include/matx/generators/ones.h
- include/matx/generators/zeros.h
- include/matx/operators/constval.h
- include/matx/transforms/cov.h
- test/00_operators/GeneratorTests.cu
- test/00_operators/OperatorTests.cu
- test/00_tensor/BasicTensorTests.cu
- test/00_tensor/EinsumTests.cu
> Created dimensionless versions of ones() and zeros()

- docs_input/CMakeLists.txt
Fixed a race-condition issue in the docs build where all of the sub folders of Doxygen were not built early enough, causing errors on docs generation.
> Multithreaded docs build Fix

- include/matx/operators/scalar_ops.h
- include/matx/operators/unary_operators.h
Add a complex sqrt function equivalent to the C++ functionality of [csqrt](https://en.cppreference.com/w/c/numeric/complex/csqrt), 
The high-level functionality supported is to always generate a complex return, even if the input is only real. I've come across situations where users sqrt negative data, with the expectation of getting complex from real.
> Implement csqrt

- docs_input/basics/nvtx.rst
- include/matx/core/nvtx.h
Enable an automatic enumeration capability to free users from needing to unique ID each range. 
Overloads the MATX_NVTX_RANGE to work with any number of parameters.
This PR also addresses an issue where all ranges created by the MATX_NVTX_RANGE macro were limited to the scope they were created in; now the NVTX range will persist until ended by the user. 
Changed the default log level to USER from internal, to not require the user to manually set the log level each time.
> Automatic Enumeration of NVTX Range IDs

- include/matx/core/half.h
> Remove conversion for double to half

- test/00_io/NvtxTests.cu
- test/CMakeLists.txt
add a series of tests for the base functions in the NVTX API, as well as the macros. 
This currently does not test the actual NVTX ranges created, just that the API can be called and compiled. there is limited testing that the IDs for ranges that are returned are sensical.
> Add NVTX Tests for Code Coverage

- CMakeLists.txt
> Change check on build type to avoid short circuiting

- docs_input/api/casting/as_complex_double.rst
- docs_input/api/casting/as_complex_float.rst
- include/matx/operators/cast.h
- include/matx/operators/concat.h
- test/00_operators/OperatorTests.cu
- test/include/test_types.h
Add complex cast operators that cast from split real and imaginary operators to cuda::std::complex
> Add complex cast operators for split inputs

- docs_input/api/math/misc/rsqrt.rst
- include/matx/core/half.h
- include/matx/operators/scalar_ops.h
- include/matx/operators/unary_operators.h
- test/00_operators/OperatorTests.cu
Adding a macro to define CUDA intrinsic math functions accessible at global scope, not in `cuda::std` namespace, calling the macro `MATX_GLOBAL_UNARY_OP_GEN`. 
Added the `rsqrt` function for computing reciprocal sqrts using the new macro. When not using the '-use_fast_math' flag, benchmarks using the hyperfine tool show `1.0/matx::sqrt` runs about 1.22x slower than 'matx::rsqrt'. Note when -use_fast_math is enabled, 1.0/sqrtf is replaced with rsqrtf, and the benchmark reflects that in similar run times with 100 runs (and 3 warmup runs).
> enh: add macro to define cuda functions accessible at global scope

- include/matx/kernels/channelize_poly.cuh
Static shared memory cannot be initialized by constructors, so the lack of trivial constructors in the std::complex types causes older CUDA toolkit releases to report an error on static shared memory declarations of complex types. Treat the memory as an aligned byte array and cast to the appropriate type as a workaround.
Fixes issue #669.
> Add workaround for pre-11.8 CTK smem init errors

- include/matx/core/error.h
New error message:
```
Incompatible operator sizes: (4,3,6) not compatible with (4,3,9)
matxException (matxInvalidSize: Incompatible operator sizes) - /repro/tmp/MatX/include/matx/operators/set.h:104
```
Closes #681
> Improved the error messages when sizes are incompatible

- include/matx/operators/norm.h
> fix type for permuted ops in norm.

- include/matx/operators/at.h
- include/matx/operators/concat.h
- include/matx/operators/frexp.h
- include/matx/operators/reshape.h
- include/matx/operators/stack.h
Closes #688 
`reshape` did not downcast the base operator to the correct type, and was inadvertently passing a shared_ptr to the device.
> Fixed base operator types

- include/matx/core/tensor_utils.h
- include/matx/operators/svd.h
- include/matx/transforms/chol/chol_cuda.h
- include/matx/transforms/chol/chol_lapack.h
- include/matx/transforms/eig/eig_cuda.h
- include/matx/transforms/eig/eig_lapack.h
- include/matx/transforms/lu/lu_cuda.h
- include/matx/transforms/lu/lu_lapack.h
- include/matx/transforms/qr/qr_cuda.h
- include/matx/transforms/qr/qr_lapack.h
- include/matx/transforms/solver_common.h
- include/matx/transforms/svd/svd_cuda.h
- include/matx/transforms/svd/svd_lapack.h
- test/00_solver/SVD.cu
- Bypassed temp allocations and having to transpose outputs in most cases for SVD
- Added m < n CUDA SVD support (cuSolver natively only supports m >= n)
- Added option to use `gesdd` or `gesvd` LAPACK driver for Host SVD
- For cuSolver batching, replaced per-iteration sync & error check with a single check at the end to reduce blocking operations
> Solver SVD Optimizations and Improved cuSolver batching

- include/matx/core/tie.h
- test/00_transform/Norm.cu
> mtie should output the correct rank and size for the output operator.

- include/matx/transforms/chol/chol_lapack.h
- include/matx/transforms/eig/eig_lapack.h
- include/matx/transforms/lu/lu_lapack.h
- include/matx/transforms/qr/qr_lapack.h
- include/matx/transforms/svd/svd_lapack.h
- Fix for [LAPACK bug](https://github.com/Reference-LAPACK/lapack/issues/600) causing incorrect workspace size calculations for single-precision routines at large matrix sizes due to float-to-int conversions (only those that may need O(n^2) space like Eig and SVD are affected)
- Removed caching in Host LU and Cholesky since no workspace is required
Misc: Renamed Host solver cache types to be lowercase for consistency
> Host Solver workspace query fix

- include/matx/transforms/inverse.h
- test/00_solver/Inverse.cu
Change the behavior of the inv() transform as follows:
- No longer unconditionally overwrite the input with factorized data. Previously, (Ainv = inv(A)).run() would write the inverse to Ainv and the LU factorization to A.
- Support in-place transforms like (A = inv(A)).run(). Previously, this would run, but the results would be incorrect because the underlying cuBLAS calls only support out-of-place solves.
- The above are achieved by always creating a temporary work buffer and copying the input into that work buffer.
- Add support for input operators (i.e., not just tensors). The operator runs when populating the temporary input work buffer.
- Use host-pinned memory and async memcpys to test the success of the factorization/inversion. This still synchronizes the provided stream, but no …
> Add in-place transform support for inv()

- include/matx/transforms/inverse.h
- test/00_solver/Inverse.cu
Use the cublas<t>matinvBatched() family of functions to invert linear systems of size N <= 32. This has two advantages over the more general pair of getrfBatched() and getriBatched() functions:
1. Higher performance with the single kernel than with split kernels.
2. The matinv functions support in-place transforms and do not modify the input in the case of out-of-place transforms, so we do not need a temporary input work buffer if the input is a tensor view.
> Use cublas<t>matinvBatched() for N <= 32

- docs_input/api/linalg/decomp/pinv.rst
- docs_input/api/linalg/other/det.rst
- include/matx/core/tensor.h
- include/matx/operators/det.h
- include/matx/operators/operators.h
- include/matx/operators/pinv.h
- include/matx/operators/svd.h
- include/matx/operators/trace.h
- include/matx/transforms/det.h
- include/matx/transforms/pinv.h
- include/matx/transforms/svd/svd_cuda.h
- include/matx/transforms/svd/svd_lapack.h
- test/00_solver/Pinv.cu
- test/00_solver/SVD.cu
- test/CMakeLists.txt
- test/test_vectors/generators/00_solver.py
- Created new `pinv()` operator for matrix pseudo-inverse using SVD in Reduced mode. Optional `rcond` parameter which is used to define the cutoff for small singular values. Singular values smaller than `rcond * largest_singular_value` are set to 0.
- Changed `SVDMode::REDUCED` interface so that U and VT tensors passed in must be of reduced size instead of the full size. That is, instead of  U being of shape `... x m x m`, it should have shape `... x m x k` where `k=min(m,n)`. Similarly VT should be of shape `... x k x n`.
- Added `det()` documentation page
Resolves #487
> Added new pinv() operator and updated Reduced SVD

- include/matx/transforms/conv.h
> Workaround for constexpr bug inside lambda in CUDA 11.8

- docs_input/api/creation/operators/diag.rst
- include/matx/generators/diag.h
- include/matx/operators/diag.h
- test/00_operators/GeneratorTests.cu
Closes #737 
Added diag operator taking 1D operator to generate 2D operator
Added k parameter to pull off-main diagonal elements
> Added diag operator taking 1D operator to generate 2D operator

- include/matx/core/tensor_impl.h
- include/matx/generators/range.h
- include/matx/operators/clone.h
- include/matx/operators/diag.h
- include/matx/operators/permute.h
gcc 13.2 and above show erroneous error messages related to uninitialized variables that are not possible. Suppress these with pragmas.
> Adding workarounds for false positives on gcc14

- include/matx/core/cache.h
Tmartin's visibility fix for static cache variables and functions.
```
__attribute__ ((visibility ("default")))
```
> Visibility fix for cache static deinit issue

- include/matx/core/defines.h
- include/matx/core/half.h
- include/matx/core/iterator.h
- include/matx/core/tensor_desc.h
- include/matx/core/tensor_impl.h
- include/matx/generators/range.h
- include/matx/operators/clone.h
- include/matx/operators/diag.h
- include/matx/operators/isclose.h
- include/matx/operators/permute.h
- include/matx/transforms/eig/eig_lapack.h
- include/matx/transforms/reduce.h
- include/matx/transforms/svd/svd_lapack.h
gcc14.1 has several erroneous error messages that are not correct related to uninitialized variables. We disable these warnings on specific lines of code for now.
> Fix for erroneous errors on gcc14.1

- include/matx/operators/concat.h
- include/matx/transforms/cub.h
- test/00_operators/ReductionTests.cu
- test/00_tensor/CUBTests.cu
The sort implementation currently requires contiguous tensor view inputs. The run-time check for that requirement is currently disabled for release builds and thus those builds can produce incorrect results for non-contiguous tensors.
This change creates temporary contiguous allocations and copies the input when necessary to support sort(). This has the side effect of adding some operator input support for sort() because the operator will execute to populate the temporary tensor.
> Create temp contiguous tensors if needed for sort

- CMakeLists.txt
`message(WARNING`  cannot be disable by the user and using `message(AUTHOR_WARNING` make it easier to disable via `-Wno-dev`
> Switch CMake warnings by author warnings to allow user to disable them

- docs_input/basics/memory.rst
- include/matx/core/allocator.h
> Added documentation of memory types

- include/matx/operators/clone.h
- include/matx/operators/collapse.h
- include/matx/operators/diag.h
- include/matx/operators/fftshift.h
- include/matx/operators/hermitian.h
- include/matx/operators/interleaved.h
- include/matx/operators/kronecker.h
- include/matx/operators/permute.h
- include/matx/operators/planar.h
- include/matx/operators/r2c.h
- include/matx/operators/remap.h
- include/matx/operators/repmat.h
- include/matx/operators/reshape.h
- include/matx/operators/reverse.h
- include/matx/operators/select.h
- include/matx/operators/self.h
- include/matx/operators/shift.h
- include/matx/operators/slice.h
- include/matx/operators/stack.h
Hide whitespace when reviewing since I fixed the alignment on a bunch of files too.
> Cleaning up non-const operator() to avoid code duplication

- docs_input/api/manipulation/selecting/reduce.rst
- include/matx/core/iterator.h
- include/matx/transforms/cub.h
- include/matx/transforms/reduce.h
- test/00_operators/ReductionTests.cu
Resolves issue #666 
Note: Existing (unrelated to this PR) main HEAD CUB cache issue opened as #773
> Switch to CUB/Thrust backend for cuda executor argmax

- include/matx/transforms/reduce.h
Might fix #678 but uses CUB not Thrust
> Change any() and all() to use CUB's reduce

- include/matx/operators/remap.h
Fix suggested by @cliffburdick for handling `remap(concat(..))`
> Change shape_type for the remap op

- examples/fft_conv.cu
- include/matx/core/cache.h
- include/matx/transforms/chol/chol_cuda.h
- include/matx/transforms/eig/eig_cuda.h
- include/matx/transforms/eig/eig_lapack.h
- include/matx/transforms/lu/lu_cuda.h
- include/matx/transforms/qr/qr_cuda.h
- include/matx/transforms/qr/qr_lapack.h
- include/matx/transforms/solver_common.h
- include/matx/transforms/svd/svd_cuda.h
- include/matx/transforms/svd/svd_lapack.h
- Add executor to solver params so allocations can happen asynchronously and can be compared for the cache.
- Add mutex around cache for multiple threads
> Fix solver interfaces to use executor in cache

- examples/CMakeLists.txt
- examples/python_integration_sample/CMakeLists.txt
- examples/python_integration_sample/example_matxutil.py
- examples/python_integration_sample/matxutil.cu
- examples/python_integration_sample/mypythonlib.py
- include/matx/core/make_tensor.h
- include/matx/core/tensor.h
- test/00_tensor/BasicTensorTests.cu
> Python integration sample

- include/matx/core/storage.h
- include/matx/core/tensor.h
- include/matx/core/tensor_impl.h
- include/matx/core/type_utils.h
- include/matx/operators/set.h
Adding first changes needed for sparse support by adding a new data template to the tensor_impl class.
> Adding structures needed for sparse support

- examples/CMakeLists.txt
- examples/sparse_tensor.cu
- include/matx/core/make_sparse_tensor.h
- include/matx/core/print.h
- include/matx/core/sparse_tensor.h
- include/matx/core/sparse_tensor_format.h
This PR introduces the implementation of a single versatile sparse tensor type that uses a tensor format DSL (Domain Specific Language) to describe a vast space of storage formats. Although the tensor format can easily define many common storage formats (such as Dense, COO, CSR, CSC, BSR), it can also define many less common storage formats. In addition, the tensor format DSL can be extended to include even more storage formats in the future.
This first PR simply introduces all storage details for the single versatile sparse tensor type, together with some factory methods for constructing COO, CSR, and CSC sparse matrices from MatX buffers. Later PRs will introduce more general ways of constructing sparse tensors (e.g. from file) and actual operations like SpMV and SpMM using cuSPARSE.
> introduce a versatile sparse tensor type to MatX (experimental)

- docs_input/api/linalg/other/cross.rst
- include/matx/operators/cross.h
- include/matx/operators/operators.h
- test/00_operators/OperatorTests.cu
- test/test_vectors/generators/00_operators.py
Takes in two operators of size A0 x ... x An x 3 (or 2) and size B0 x ... x Bn x (3 or 2) with matching batch sizes and computes the cross product. If both input operators have size = 2 on the last dimension, the size of the output's last dimension is 1 and only contains the z component of the output. This is contrary, but as similar to, the NumPy implementation which drops the rank of the output by 1 if both inputs are in-plane vectors. Doing so in MatX does not seem straightforward since `Rank` is a static method and we may not know the sizes of A and B (e.g. 2 or 3 on the last dimension) at the time the rank is determined, but those sizes affect the rank of `cross` if we followed NumPy's approach.
> Add cross product operator

- examples/sparse_tensor.cu
- include/matx/core/sparse_tensor_format.h
Although unlikely to be useful, the "Scalar" form is a valid storage format in the full space of storage formats that can be described by the DSL. This minor change ensures those cases do not result in compile-time errors.
> Guard all DIM/LVL recursion against completely empty format

- test/00_operators/OperatorTests.cu
- test/test_vectors/generators/00_operators.py
The cross product unit tests failed sometimes for half types, so increased the threshold for half types.
> Adjust half-type threshold for cross product unit tests

- examples/sparse_tensor.cu
- include/matx/core/make_sparse_tensor.h
- include/matx/core/sparse_tensor.h
- include/matx/core/sparse_tensor_format.h
- include/matx/core/tensor_impl.h
Note that is a fully functional "locator" for the () operator that works for *all* versatile sparse tensors. Currently, the operator is defined at sparse_tensor level, but it should be moved into tensor_impl after this. Also, clients should always be aware that the () operator for compressed levels are *not* random-access, but involve a search to find if the element is stored.
> Implement the () operator on sparse tensors

- include/matx/core/print.h
- test/00_operators/OperatorTests.cu
Add a new matx::print() implementation that accepts one or more arguments to specify the number of elements to print in the given dimension. This uses the pre-existing matx::fprint(stdout, ...) function.
> Add print function with nonzero dim args

- include/matx/core/sparse_tensor_format.h
Rationale:
Even though the versatile sparse tensor is able to define tensor storage as well, we will not use that feature inside the MatX library. So the testers will never be used.
> Remove dense "testers" from the sparse tensor format type

- include/matx.h
MatX requires CUDA compute capability / architecture 6.0 (Pascal) or newer. Building for an older version, such as 5.2 (Maxwell), results in errors due to missing atomic support for some data types. Add an explicit check to the matx.h header to generate an earlier compile-time error that specifies the minimum architecture requirement.
> Add compile-time check for minimum CUDA arch

- include/matx/file_io/tiff.h
When matx.h is included in a .cpp file and libnvtiff is present on the system, there is an initializer list ordering error during compilation:
```
In file included from /build/_deps/matx-src/include/matx/file_io/file_io.h:50,
from /build/_deps/matx-src/include/matx.h:44,
from /workspace/src/test.cpp:2:
/build/_deps/matx-src/include/matx/file_io/tiff.h: In constructor 'matx::io::Tiff::Tiff(cudaStream_t, int)':
/build/_deps/matx-src/include/matx/file_io/tiff.h:135:22: error: 'matx::io::Tiff::stream_' will be initialized after [-Werror=reorder]
135 |         cudaStream_t stream_;
|                      ^~~~~~~
/build/_deps/matx-src/include/matx/file_io/tiff.h:133:13: error:   'int matx::io::Tiff::NUM_DECODERS_' [-Werror=reorder]
133 |         int NUM_DECODERS_;
|             ^~~~~~~~~~~~~ …
```
> Fix initializer list order

- include/matx/core/make_sparse_tensor.h
Rationale:
This ensures COO/CSR/CSC have proper data arrays
for initialization, to get consistent storage.
> Add user-friendly assertions to make_sparse_tensor

- include/matx/transforms/matmul/matmul_cusparse.h
- test/00_sparse/Matmul.cu
> allow for incoming/outgoing transformations on SpMM

- docs_input/api/signalimage/general/pwelch.rst
- examples/pwelch.cu
- include/matx/kernels/pwelch.cuh
- include/matx/operators/pwelch.h
- include/matx/transforms/pwelch.h
- test/00_operators/PWelch.cu
- test/test_vectors/generators/00_operators.py
This PR addresses concerns in issue #887:
* Configurable scaling is supported.  Density and Spectrum modes, similar to Matlab or scipy.signal, as well as fused dB modes frequently needed for spectrum-analyzer-like plotting
* Custom reduction kernel is used instead of MatX sum() using CUB DeviceSegmentedReduce (DSR).
Three reasons why the custom reduction kernel is preferred:
1. In the nominal case where the input signal is a memory backed complex-valued tensor and the output power spectrum is a memory backed real-valued tensor, the intermediate overlapping signal is a 2D tensor {batches, nfft}.  This is an optimal memory layout for the FFTs, but a very suboptimal layout for CUB DSR which would the permuted layout {nfft, batches} as CUB DSR uses one block of threads to read all the …
> Add configurable Pwelch scaling and improve performance

- docs_input/api/linalg/decomp/qr.rst
- include/matx/operators/qr.h
- include/matx/transforms/qr/qr_cuda.h
- include/matx/transforms/svd/svd_cuda.h
- test/00_solver/QREcon.cu
- test/CMakeLists.txt
Added an economic qr calling the cusolver orgqr methods based on appropriate type of the input. Did not replace `qr_solver` so as to keep existing functionality, but expanded on it. Modifying the existing `qr` transform to perform an economic QR seems to lead to numeric instability, and `QH * Q` is not near identity in that case, and `Q*R` is not near the input operator.  The` static_cast`s to `int` in the `orgqr_dispatch` functions prevent narrowing errors at compilation.
To catch an edge case error, I modified the hashing function slightly to use the rank of the input as part of the hash to prevent `bad any_cast` when using a cached plan. Previously an error was thrown if one firsts performs a batched economic QR on a tensor of shape` {b, m, n}` with `b = 1`, then run a plan on a tensor …
> feat: added economic QR

- include/matx/core/sparse_tensor_format.h
- include/matx/core/tensor_impl.h
(1) finishes TODO on lvl type to include properties
(2) adds more constexpr test methods and shortcuts
(3) improves readability to format decls and testers
> Improve tensor format types

- CMakeLists.txt
- include/matx.h
- include/matx/core/defines.h
By default, libcudacxx includes additional checking for NaN/Inf combinations for complex multiplication and division. This is not required by the C++ Standard and is not the way a typical user would define these operations for themselves. For example, complex multiplication between x and y would typically be implemented as:
std::complex prod(
x.real()*y.real() - x.imag()*y.imag(),
x.real()*y.imag() + x.imag()*y.real());
This implementation does not include any special handling for NaN/Inf values and it will outperform implementations that include such handling.
Thus, MatX now defaults to the "simple" implementation of the operations. If the extra checks (see Annex G of the C11 specification for details) are needed, then the user can enable these checks by defining the …
> Disable additional NaN/Inf checks for complex ops

- docs_input/api/creation/operators/linspace.rst
- examples/spectrogram.cu
- examples/spectrogram_graph.cu
- include/matx/generators/chirp.h
- include/matx/generators/linspace.h
- test/00_operators/GeneratorTests.cu
- test/00_operators/legendre_test.cu
- test/00_operators/overlap_test.cu
- test/00_operators/slice_and_reduce_test.cu
- test/00_operators/slice_and_reshape_test.cu
- test/00_operators/slice_test.cu
- test/00_tensor/EinsumTests.cu
The old linspace syntax used a template parameter to essentially describe how the 1D vector was cloned. This is not how python does linspace, and is very limited in value since `clone` does the same thing. This change follows the Python syntax by allowing a vector of start/stops such that every row/column can be different.
Closes #929
> Update linspace for more of a pythonic syntax

- CMakeLists.txt
- include/matx/core/pybind.h
The MATX_ROOT macro is another thing that has been around since the beginning, but really just adds an extra dependency for running the tests that's not needed. This PR removes it to make it a relative path instead.
> Remove MATX_ROOT macro

- cmake/GetGTest.cmake
GTest 1.11.0 specifies a minimum version of CMake 2.8, which triggers a hard error in CMake 4.0 as support for it has been removed. This has been fixed in later versions of GTest.
This was discovered while testing new devcontainers on CCCL: https://github.com/NVIDIA/cccl/actions/runs/14206091102/job/39804067192?pr=4302
```
Call Stack (most recent call first):
/home/coder/cccl/build/cuda12.8ext-gcc13/matx/build/cmake/CPM_0.40.0.cmake:1074 (FetchContent_Populate)
/home/coder/cccl/build/cuda12.8ext-gcc13/matx/build/cmake/CPM_0.40.0.cmake:868 (cpm_fetch_package)
/home/coder/cccl/build/cuda12.8ext-gcc13/matx/build/cmake/CPM_0.40.0.cmake:306 (CPMAddPackage)
cmake/GetGTest.cmake:40 (CPMFindPackage)
cmake/GetGTest.cmake:71 (find_and_configure_gtest)
CMakeLists.txt:402 (include)
This warning is …
```
> Bump GTest version for CMake 4.0 compatibility.

- docs_input/api/manipulation/joinrepeat/clone.rst
- include/matx/operators/clone.h
- test/00_operators/clone_test.cu
- fix typo
- quote symbol
- fix dimension (1D should be 0D)
- add 1D example using matxKeepDim
> Improve clone docs

- docs_input/api/math/misc/interp.rst
- examples/CMakeLists.txt
- examples/interpolate.cu
- include/matx/operators/interp.h
- include/matx/operators/operators.h
- test/00_operators/CMakeLists.txt
- test/00_operators/interp_test.cu
Fixes #926 
Implements linear interpolation, as well as piecewise constant (nearest, next, previous).
Some questions it would be good to get some input on:
At the moment, it just extrapolates the boundary value as piecewise constant. 
- [Matlab](https://www.mathworks.com/help/matlab/ref/double.interp1.html#btwp6lt-1-extrapolation) fills with NaNs by default. 
- We could also support linear extrapolation (from the 2 points closest to the neighbor)
- numpy supports periodic domains.
Currently this is implemented as a regular operator, so each point is interpolated independently. There is probably room to optimize this (though the optimal pattern will probably depend on the sizes of `x` and `xq`). cc @tmartin-gh 
I haven't yet implemented the equally-spaced case yet, which would let us avoid …
> implement basic interp

- include/matx/transforms/cub.h
- test/00_operators/ReductionTests.cu
This fixes #946 by performing a copy of the operator to a temporary tensor.
> Fix ExecArgReduce compile error with matxBinaryOp

- include/matx/operators/collapse.h
- include/matx/operators/concat.h
- include/matx/operators/normalize.h
- include/matx/operators/overlap.h
- include/matx/operators/remap.h
- include/matx/operators/slice.h
- include/matx/operators/stack.h
- include/matx/operators/transpose.h
- include/matx/transforms/conv.h
Fixes issue GH-953. The conv1d operator uses std::conditional_t<> to define a local shape_type depending on the shape_type trait of the output operator. When combined with an output operator lacking a shape_type trait, this yields a build error.
Relatively few operators include a public shape_type trait, although the tensor_desc_t struct does include shape_type. This commit removes public shape_type traits from current operators that define them, but does allow private shape_type types for internal use. For conv1d, shape_type is replaced by index_t. shape_type is still used in the tensor descriptors.
> Fix build error using shape_type in std::conditional_t

- include/matx/operators/scalar_ops.h
- test/00_operators/operator_func_test.cu
As an optimization, use sincos() to compute the real and imaginary components of expj() rather than separate sin() and cos(). Also update the expj example in the documentation and add new test cases.
> Use sincos() rather than separate sin/cos for expj

- include/matx/core/error.h
Prevents `MATX_CUDA_CHECK(cudaGetLastError())` from printing 'no error' due to possible multiple evaluation of the input.
> Refactor MATX_CUDA_CHECK to prevent multiple evaluation

- examples/sparse_tensor.cu
- include/matx/core/make_sparse_tensor.h
- include/matx/core/sparse_tensor_format.h
- include/matx/kernels/matvec.cuh
- include/matx/transforms/matmul/matvec_cusparse.h
DIA-J is most common but DIA-I is used by cuSPARSE legacy
> Generalize DIA to DIA-I and DIA-J

- include/matx/executors/host.h
When including `using namespace matx;` in a source file, the cpu_set_t type will be ambiguous if later including <sched.h> or some other dependency that includes <sched.h> and uses cpu_set_t.
> Avoid name collision with cpu_set_t from sched.h

- examples/sparse_tensor.cu
- include/matx/operators/solve.h
- include/matx/transforms/solve/solve_cudss.h
- test/00_sparse/Solve.cu
Since all sparse direct solvers expect X and B in column-major format, it is better to adjust our definition for solve() than to insert artificial and costly data transpositions everywhere. Also, presenting the different rhs vectors and solutions along rows is more natural for a lot of direct solver problems.
> Let X = solve(A, B) take X and B along rows

- examples/sparse_tensor.cu
- include/matx/operators/solve.h
- include/matx/transforms/solve/solve_cusparse.h
- test/00_sparse/Dia.cu
This uses cuSPARSE's legacy API to solve a tri-diagonal matrix direct solve operation (lower diagonal, main diagonal, upper diagonal). This involves a run-time check on DIA (which is more general) to ensure only those three diagonals are used.
> Add tri-diagonal solve support

- include/matx/core/sparse_tensor_format.h
even though this is not used anywhere yet, the DIA formats require
this correction for the proper inverse (restricted to proper
compressed-range pairs for now)
> proper lvl2dim computation for add/sub

- include/matx/core/half.h
- include/matx/operators/scalar_ops.h
I have a PR open that properly implements `fmod` and `modf` for all supported floating point types.
However, that creates an ambigouity with the `fmod` definition in scalar_ops, because the MatX  half wrapper is convertible to both float *and* the half type.
Avoid this by specializing that function as we do for `exp`
> Avoid `fmod` become ambiguous once CCCL specializes it for extended floating point types

- test/00_sparse/Dia.cu
Note, this is waiting for https://github.com/NVIDIA/MatX/pull/999
> test for batched tri-diag direct solver

- include/matx/operators/reverse.h
- test/00_operators/reverse_test.cu
The current `flipud` logic caused a compilation error when using it with 1D arrays. Changing the logic to seems to fix the issue. Added tests.
> fix flipud for 1D tensors

- docs_input/api/searchsort/find_peaks.rst
- include/matx/core/type_utils.h
- include/matx/operators/find_peaks.h
- include/matx/operators/operators.h
- include/matx/transforms/cub.h
- include/matx/transforms/find_peaks.h
- test/00_operators/CMakeLists.txt
- test/00_operators/find_peaks.cu
- test/00_operators/operator_test_types.hpp
- test/include/test_types.h
Added a `find_peaks` operator similar to SciPy's. So far only threshold and height are implemented. Other parameters like `distance` require a second reduction and can be added if needed.
Closes #603
> Added `find_peaks` operator

- include/matx/operators/base_operator.h
- include/matx/operators/collapse.h
- include/matx/operators/concat.h
- include/matx/operators/overlap.h
- include/matx/operators/permute.h
- include/matx/operators/remap.h
- include/matx/operators/reshape.h
- include/matx/operators/reverse.h
- include/matx/operators/shift.h
- include/matx/operators/slice.h
- include/matx/operators/stack.h
- include/matx/operators/transpose.h
- include/matx/operators/updownsample.h
When a statement `op = transform` occurred where op was not a tensor, the transform was being called twice incorrectly leading to poor performance. This simplifies the code and calls it once.
> Fixed issue where op=transform was double-calling transform

- docs_input/api/manipulation/joinrepeat/pad.rst
- include/matx/operators/operators.h
- include/matx/operators/pad.h
- test/00_operators/CMakeLists.txt
- test/00_operators/pad_test.cu
The pad operator supports pre- and post-padding with constant pad values and edge padding.
Closes Issue #451
> Add pad operator for padding input operators along one dimension

- docs_input/api/manipulation/rearranging/zipvec.rst
- include/matx/core/tensor_impl.h
- include/matx/core/type_utils.h
- include/matx/core/vector.h
- include/matx/operators/operators.h
- include/matx/operators/zipvec.h
- test/00_operators/CMakeLists.txt
- test/00_operators/zipvec_test.cu
Add a new zipvec operator that zips multiple input operators into a vectorized operation (e.g., an operator with type float3 when zipping x, y, and z coordinates). 
The input operators must have the same rank and size in all dimensions and the types must be compatible where compatible means that we can convert each input to the derived output type without narrowing. For types char, short, int, long (and their unsigned variants) and float/double, the vector size can be 1-4 elements. For __half, only length-2 vectors are supported. The components from the input operators are accessed by the fields x, y, z, and w, respectively, in the zipped operator.
> Add zipvec operator

- include/matx/core/type_utils.h
- include/matx/core/vector.h
- Add CUDA version detection for double4, long4, ulong4, longlong4, ulonglong4
- Use _32a suffix variants for CUDA 13+ compatibility
- Maintain backward compatibility with legacy vector type names for older CUDA versions
- Conditional compilation based on __CUDACC_VER_MAJOR__ >= 13
Affected files:
- include/matx/core/vector.h: Updated alignment checks and type comparisons
- include/matx/core/type_utils.h: Added conditional VecTypeSelector specializations
> Add conditional CUDA 13+ support for select vector types

- docs_input/api/creation/tensors/make.rst
- include/matx/core/make_sparse_tensor.h
- include/matx/core/make_tensor.h
- include/matx/core/sparse_tensor.h
- include/matx/core/storage.h
- include/matx/core/tensor.h
- include/matx/core/tensor_desc.h
- include/matx/core/tensor_impl.h
- include/matx/core/type_utils.h
- include/matx/kernels/matvec.cuh
- include/matx/operators/set.h
- include/matx/transforms/convert/dense2sparse_cusparse.h
- include/matx/transforms/convert/sparse2sparse_cusparse.h
- test/00_misc/AllocatorTests.cu
- test/00_tensor/Storage.cu
- test/CMakeLists.txt
- Replace template-based Storage with unified Storage<T> class
- Remove inheritance requirement from pmr_allocator_interface
- Implement pure duck typing - users just need allocate()/deallocate() methods
- Add SFINAE detection for both allocator objects and pointers
- Support owning/non-owning constructors with optional custom allocators
- Eliminate dynamic allocation overhead for common allocator cases
- Maintain backward compatibility with legacy sparse tensor types
- Add comprehensive unit tests for duck-typed allocator system
- Organize tests in new test/00_misc/ directory following MatX conventions
This provides maximum flexibility while removing inheritance requirements and virtual function overhead. Users can now implement any allocator without inheriting from base classes - if it …
> Refactor Storage system to use duck-typed allocators

- CMakeLists.txt
Already works since transitive dependency through cusolver, but since we include cusparse directly in matx' interface header, it's better to be explicit and mark cusparse as a direct link dep.
> Add cusparse explicitly to link libraries

- cmake/versions.json
- include/matx/transforms/cub.h
Add optimized fixed-size segmented reduce support for CUB 3.2+
Implement conditional support for CUB's new fixed-size segmented reduction API
when using CUB version 3.2 or higher. This optimization applies to both generic
reduce and sum operations when:
- Input is a tensor view
- Both input and output tensors are contiguous memory
- All segments have uniform size
The new implementation uses CUB's simplified API that takes a segment size
parameter instead of begin/end iterators, providing better performance for
uniform segment reductions.
Changes:
- Add version checks for CUB_MAJOR_VERSION >= 3 && CUB_MINOR_VERSION >= 2
- Implement fast path using fixed segment size for contiguous tensors
- Fall back to iterator-based API for non-contiguous or non-uniform cases
- Apply optimization to both …
> Fixed-size reductions

- docs_input/api/dft/fft/fft.rst
- docs_input/api/dft/fft/fft2d.rst
- docs_input/api/dft/fft/ifft.rst
- docs_input/api/dft/fft/ifft2.rst
- docs_input/api/searchsort/argsort.rst
- docs_input/api/searchsort/sort.rst
- docs_input/api/signalimage/convolution/conv1d.rst
- docs_input/api/signalimage/convolution/conv2d.rst
- docs_input/api/stats/corr/corr.rst
- include/matx/kernels/conv.cuh
- include/matx/operators/pad.h
- include/matx/transforms/cub.h
- include/matx/transforms/fft/fft_common.h
Some of the operators were missing documentation on their enum parameters. This covers all missing parameters.
Closes #574
> Added enum documentation for all operators
