NVIDIA/MatX

- include/kernels/matx_conv_kernels.cuh
- include/kernels/matx_filter_kernels.cuh
- include/kernels/matx_transpose.cuh
- include/kernels/matx_utility_kernels.cuh
- include/matx_allocator.h
- include/matx_conv.h
- include/matx_cub.h
- include/matx_defines.h
- include/matx_exec_host.h
- include/matx_exec_kernel.h
- include/matx_executor.h
- include/matx_random.h
- include/matx_reduce.h
- include/matx_tensor.h
- include/matx_tensor_ops.h
- BETA: Adding support for executing operators on the host
- Added support for compiling using a host compiler only (no nvcc)
> Host operators

- include/matx_reduce.h
- include/matx_shape.h
- include/matx_tensor.h
- include/matx_type_utils.h
- test/00_operators/ReductionTests.cu
> Adding argmin/argmax functions

- README.md
- docs/limitations.rst
- docs/quickstart.rst
- include/matx_allocator.h
- include/matx_exec_kernel.h
- include/matx_reduce.h
- include/matx_scalar_ops.h
- include/matx_tensor.h
- include/matx_tensor_ops.h
- include/matx_tensor_utils.h
- include/matx_type_utils.h
- test/00_operators/OperatorTests.cu
Adds support for executing certain operators on the host. Currently this is limited to basic operators that use `.run()`, but we're investigating adding support for other executors as well.
> Added support for host operators

- include/kernels/matx_transpose.cuh
- include/matx_conv.h
- include/matx_reduce.h
- include/matx_set.h
- include/matx_shape.h
- include/matx_tensor.h
- include/matx_tensor_impl.h
- include/matx_tensor_ops.h
- include/matx_type_utils.h
- test/00_tensor/BasicTensorTests.cu
Added shim layer to reduce tensor size on device
> Reduced tensor size

- include/matx_tensor_impl.h
- include/matx_tensor_ops.h
- test/00_operators/OperatorTests.cu
> Added concatenate operator with unlimited tensors

- README.md
> Add test CI file

- CMakeLists.txt
- cmake/FindNvshmem.cmake
- cmake/FindcuTENSOR.cmake
- cmake/FindcuTensorNet.cmake
- docs_input/api/einsum.rst
- docs_input/api/index.rst
- include/matx_einsum.h
- include/matx_error.h
- include/matx_type_utils.h
- test/00_tensor/ContractionTests.cu
- test/CMakeLists.txt
- test/test_vectors/generators/00_operators.py
Added support for tensor contractions using ``einsum`` notation.
> Contraction

- docs_input/api/einsum.rst
- docs_input/api/reduce.rst
- include/matx_einsum.h
- include/matx_reduce.h
- test/00_operators/ReductionTests.cu
- test/00_tensor/ContractionTests.cu
Added more einsum tests and trace function
> Einsum tests

- include/matx_tensor.h
Added the missing `()` after `->begin`.
> Fix SetVals for rank-4 tensors

- docs_input/notebooks/exercises/example1_adv_slice_col.cu
- docs_input/notebooks/exercises/example1_adv_slice_row.cu
- docs_input/notebooks/exercises/example1_clone.cu
- docs_input/notebooks/exercises/example1_init.cu
- docs_input/notebooks/exercises/example1_permute.cu
- docs_input/notebooks/exercises/example1_simple_slice.cu
- docs_input/notebooks/exercises/example2_assignment1.cu
- docs_input/notebooks/exercises/example2_conditional.cu
- docs_input/notebooks/exercises/example2_eye.cu
- docs_input/notebooks/exercises/example2_hamming.cu
- docs_input/notebooks/exercises/example2_init.cu
- docs_input/notebooks/exercises/example2_mixed_rank.cu
- docs_input/notebooks/exercises/example2_multiple_ops.cu
- docs_input/notebooks/exercises/example2_rand.cu
- docs_input/notebooks/exercises/example2_scalar.cu
- docs_input/notebooks/exercises/example2_tensor_add.cu
- docs_input/notebooks/exercises/example2_tensor_div.cu
- docs_input/notebooks/exercises/example2_viz.cu
- docs_input/notebooks/exercises/example3_1dfft.cu
- docs_input/notebooks/exercises/example3_2dfft.cu
- docs_input/notebooks/exercises/example3_assignment1.cu
- docs_input/notebooks/exercises/example3_conv1d.cu
- docs_input/notebooks/exercises/example3_conv2d.cu
- docs_input/notebooks/exercises/example3_fft_conv.cu
- docs_input/notebooks/exercises/example3_full_reduce.cu
- docs_input/notebooks/exercises/example3_gemm.cu
- docs_input/notebooks/exercises/example3_partial_reduce.cu
> Updated notebook examples

- include/matx_cub.h
- test/00_operators/ReductionTests.cu
> Added find() function

- docs_input/api/reduce.rst
- include/matx_cub.h
- include/matx_tensor.h
- test/00_operators/ReductionTests.cu
> Add unique() function

- include/matx_tensor_impl.h
- include/matx_type_utils.h
- include/matx_utils.h
- test/00_transform/Cov.cu
- test/00_transform/MatMul.cu
- test/include/utilities.h
> Fixing P100 unit tests

- include/matx_matmul.h
- test/00_transform/MatMul.cu
- test/test_vectors/generators/00_transforms.py
> Fixed transposed GEMMs

- bench/00_operators/reduction.cu
- examples/convolution.cu
- examples/spectrogram.cu
- include/matx_cub.h
- include/matx_radar.h
- include/matx_reduce.h
- include/matx_solver.h
- include/matx_tensor.h
- include/matx_tensor_desc.h
- include/matx_tensor_generators.h
- include/matx_tensor_impl.h
- include/matx_tensor_ops.h
- include/matx_tensor_utils.h
- include/matx_type_utils.h
- test/00_operators/ReductionTests.cu
- test/00_solver/Eigen.cu
- test/00_tensor/CUBTests.cu
- test/00_tensor/TensorCreationTests.cu
Switched to using CUB for operators where possible. Gives a 2-4x speedup in the best cases.
> CUB operators

- include/matx_reduce.h
- test/00_operators/ReductionTests.cu
> Fixed bug with wrong type on argmin/max

- include/matx_fft.h
- include/matx_make.h
- include/matx_matmul.h
Also rearranged template parameters on make_tensor so `owning` comes first.
> Fixed bug with matmul use-after-free

- include/matx_error.h
Closes #177 
Found by @ZJUGuoShuai
> Added missing assert in release mode

- include/matx_reduce.h
- test/00_operators/ReductionTests.cu
> Fixed argmax initialization value

- CMakeLists.txt
ccmake shoud be able to configure project.
> Fix issue #199

- include/matx_cub.h
…opy), allowed operators on more types, and fixed caching on sort
> Various CUB fixes -- got rid of offset pointers (async allocation + copy), allowed operators on more types, and fixed caching on sort

- include/matx_einsum.h
Close #240.
@ZJUGuoShuai any chance you can verify this patch? 🙂
> Fix cuTensorNet workspace size

- include/matx/kernels/conv.cuh
> Fixed conv SAME mode

- include/matx/core/storage.h
- include/matx/operators/clone.h
- include/matx/operators/permute.h
- include/matx/transforms/cub.h
- include/matx/transforms/filter.h
- test/00_operators/OperatorTests.cu
Fixed compile-time and runtime issues with release mode
> Fixed compiler errors in release mode

- include/matx/transforms/fft.h
- test/00_transform/FFT.cu
> Fixed bug with FFT size shorter than length of tensor

- include/matx.h
- include/matx/core/viz.h
- test/00_tensor/VizTests.cu
> Fixed visualization tests

- cmake/CheckPythonLibs.cmake
Variable required_python_packages was not defined.
> Fix cmake function check_python_libs.

- docs_input/api/tensorops.rst
- include/matx/operators/permute.h
- include/matx/transforms/transpose.h
- test/00_host/OperatorTests.cc
Added transpose operator
Added transpose transform for SingleThreadedHostExecutor Enabled more unit tests
> Transpose operators changes

- include/matx/generators/linspace.h
- include/matx/generators/meshgrid.h
- test/00_operators/GeneratorTests.cu
Update Meshgrid APIs to work with ND tensors and return operators for the output tensors.
> Meshgrid API Changes

- bench/00_operators/reduction.cu
- include/matx/transforms/reduce.h
- test/00_operators/ReductionTests.cu
disable median collapse operators for now
> added 4d reduction benchmark

- include/matx/core/get_grid_dims.h
- include/matx/transforms/reduce.h
- test/00_operators/ReductionTests.cu
> bug fix in get_grid_dims when z dim was > 64

- include/matx/core/tensor.h
- include/matx/core/tensor_desc.h
- include/matx/core/utils.h
- include/matx/operators/constval.h
- include/matx/operators/permute.h
- include/matx/transforms/fft.h
- include/matx/transforms/reduce.h
- test/00_transform/FFT.cu
PR working towards supporting dimensions selection and operators support.  Not ready for review.
> Support axis selection and operators in FFTs

- include/matx/operators/permute.h
- include/matx/operators/set.h
- include/matx/transforms/matmul.h
- test/00_transform/MatMul.cu
Adding axis support to gemms.
Fixed some bugs in gemms.
Now ready for review
> Adding axis support to gemms.

- include/matx/core/storage.h
> Fixed dangling reference found by valgrind

- CMakeLists.txt
- include/matx/transforms/cub.h
- include/matx/transforms/reduce.h
including bumping libcudacxx to 1.8.1
> Fixed errors related to CUDA 12 update

- include/matx/transforms/matmul.h
- test/00_transform/MatMul.cu
- test/test_vectors/generators/00_transforms.py
Fixes : https://github.com/NVIDIA/MatX/issues/353
> matmul: support real/complex tensors

- include/matx/transforms/matmul.h
Fixed another issue where we didn't detect row/col major correctly.  In this case it was when performing a cross product (Nx1 * 1xM).
> cublasLT col major detection fix.

- CMakeLists.txt
- include/matx/core/defines.h
- include/matx/core/tensor_desc.h
- include/matx/core/tensor_impl.h
- include/matx/core/tensor_utils.h
- include/matx/transforms/cub.h
- include/matx/transforms/fft.h
- include/matx/transforms/matmul.h
Fixes for 32b mode and disable CUB caching
> Fixes for 32b mode

- include/matx/core/dlpack.h
- include/matx/core/tensor.h
- include/matx/core/tensor_utils.h
- test/00_tensor/BasicTensorTests.cu
> DLPack support

- include/matx/transforms/reduce.h
- test/00_operators/ReductionTests.cu
- test/test_vectors/generators/00_operators.py
> Added delta degrees of freedom on var() to mimic Python

- include/matx/core/file_io.h
- include/matx/core/pybind.h
- test/00_io/FileIOTests.cu
This attempts to force cast the ndarray to be c-style via pybind11 and then copies the data.
> NumpyToTensorView overload which returns new TensorView

- docs_input/api/tensorgenerators.rst
- include/matx/core/tensor_utils.h
- include/matx/generators/fftfreq.h
- include/matx/generators/linspace.h
- test/00_operators/GeneratorTests.cu
- test/test_vectors/generators/01_signal.py
- Adds `fftfreq()` function to mirror SciPy's
- Reordered `print()` function for proper lookup order
> Added fftfreq() generator

- docs_input/api/manipulation/selecting/at.rst
- docs_input/api/stats/misc/percentile.rst
- examples/fft_conv.cu
- include/matx/core/make_tensor.h
- include/matx/operators/at.h
- include/matx/operators/operators.h
- include/matx/operators/percentile.h
- include/matx/transforms/percentile.h
- test/00_operators/OperatorTests.cu
- test/00_operators/ReductionTests.cu
- test/test_vectors/generators/00_reductions.py
> Added at() and percentile() operators

- docs_input/api/manipulation/rearranging/overlap.rst
- examples/spectrogram.cu
- examples/spectrogram_graph.cu
- include/matx/core/tensor.h
- include/matx/operators/operators.h
- include/matx/operators/overlap.h
- test/00_operators/OperatorTests.cu
- test/00_tensor/ViewTests.cu
Added `overlap` operator for counterpart to tensor `OverlapView`
> Add overlap operator

- docs_input/api/signalimage/general/pwelch.rst
- examples/CMakeLists.txt
- examples/pwelch.cu
- include/matx/operators/operators.h
- include/matx/operators/overlap.h
- include/matx/operators/pwelch.h
- include/matx/transforms/pwelch.h
- test/00_transform/PWelch.cu
- test/CMakeLists.txt
- test/test_vectors/generators/00_transforms.py
This PR addresses https://github.com/NVIDIA/MatX/issues/279
> Add pwelch operator

- docs_input/api/signalimage/general/pwelch.rst
- include/matx/core/pybind.h
- include/matx/operators/pwelch.h
- include/matx/transforms/pwelch.h
- test/00_operators/PWelch.cu
- test/CMakeLists.txt
- test/test_vectors/generators/00_operators.py
- test/test_vectors/generators/00_transforms.py
This PR adds support for using window functions with the pwelch operator.
> Add window operator input to pwelch

- include/matx/core/tensor_impl.h
- include/matx/operators/fft.h
- include/matx/operators/r2c.h
- test/00_operators/OperatorTests.cu
- test/00_transform/FFT.cu
Fixes a few issues with fft related type and size deductions, especially when composed with other operators.
> PreRun support for r2c and other fft related fixes

- include/matx/operators/at.h
- include/matx/operators/clone.h
- include/matx/operators/diag.h
- test/00_operators/GeneratorTests.cu
- test/00_operators/OperatorTests.cu
Add nested transform tests for at, clone, and diag operators.
> Add PreRun and tests for at/clone/diag operators

- .github/workflows/blossom-docs.yml
- docs_input/conf.py.in
This change will build the MatX docs when a PR is merged to main.
> Automatically publish docs to GH Pages on merge to main

- docs/_sources/fundamentals/datatype.rst
- docs_input/basics/datatype.rst
Fix typo s/whereever/wherever/
> chore: Fix typo s/whereever/wherever/

- include/matx/executors/kernel.h
During the last iteration when expanding the linear index into the N-D tensor index, there may be an out-of-bounds read access into the sizes array. The result of the read is unused and the iteration count is known at compile time, so the read may be removed by the compiler. Extract the last iteration into an epilogue to guarantee no out-of-bounds access.
> Prevent potential oob read in matxOpTDKernel

- include/matx/core/error.h
adding file name and line number to ease debug in MATX_CUDA_CHECK
> adding file name and line number to ease debug

- include/matx/operators/channelize_poly.h
- include/matx/transforms/channelize_poly.h
- test/00_transform/ChannelizePoly.cu
- test/test_vectors/generators/00_transforms.py
Add support for mixing precisions of the input and filter for channelize_poly.
> Add mixed precision support for channelize_poly

- CMakeLists.txt
> Change cmake option/project order

- include/matx/executors/support.h
- include/matx/operators/conv.h
- include/matx/operators/corr.h
- include/matx/operators/filter.h
- include/matx/transforms/conv.h
- include/matx/transforms/corr.h
- include/matx/transforms/filter.h
- test/00_operators/OperatorTests.cu
- test/00_transform/ConvCorr.cu
- test/00_transform/FFT.cu
- Enabled 1D FFT convolution for host
- Enabled more FFT unit tests for host
> Enabled FFT conv for host

- include/matx/core/storage.h
Fixed issue when C++20 is enabled
> Fix c++20 warning

- examples/repro.cu
NB changed the storage location of distances to managed memory (not device memory)
> Adding example to show distances is all zero.

- include/matx/transforms/cub.h
update all the code in cub.cu to use the new method of creating cub plans for the cache
> Update Cub Cache Creation to new Method

- include/matx/core/half.h
- include/matx/core/storage.h
- include/matx/operators/scalar_ops.h
> Fixed issues with host compiler with C++17 and C++20 modes

- include/matx/generators/random.h
- include/matx/transforms/solver_common.h
Fixed issue with CPU aliases in wrong namespace
Fixes #714
> Fixed random pre/post run signature

- docs_input/api/linalg/decomp/chol.rst
- docs_input/api/linalg/decomp/inverse.rst
- docs_input/api/linalg/decomp/lu.rst
- docs_input/api/linalg/decomp/qr.rst
- docs_input/api/linalg/decomp/svd.rst
- docs_input/api/linalg/eigenvalues/eig.rst
- include/matx/operators/chol.h
- include/matx/operators/det.h
- include/matx/operators/eig.h
- include/matx/operators/inverse.h
- include/matx/operators/lu.h
- include/matx/operators/pinv.h
- include/matx/operators/qr.h
- include/matx/operators/svd.h
- include/matx/transforms/solver_common.h
Updated Solver documentation for more clarity on how to use and any limitations
- Added shape, dtype, and return type documentation
- Linked Solver enum documentation to the Doxygen documentation
> Updated Solver documentation

- include/matx/core/tensor_utils.h
> Allow printing const pointers

- include/matx/transforms/cub.h
> cub.h CUDACC guards for custom ops

- docs_input/developer_guide/docs.rst
- docs_input/developer_guide/index.rst
- docs_input/developer_guide/operators.rst
- docs_input/developer_guide/transforms.rst
- docs_input/index.rst
- include/matx/operators/collapse.h
Added developer guides for writing operators, transforms, and updating docs.
> Updating developer documentation

- include/matx/core/allocator.h
> Add a better error on memory allocation failure

- cmake/versions.json
> Make CCCL copy false

- include/matx/transforms/convert/dense2sparse_cusparse.h
- include/matx/transforms/convert/sparse2dense_cusparse.h
- include/matx/transforms/matmul/matmul_cusparse.h
- include/matx/transforms/solve/solve_cudss.h
- test/00_sparse/Matmul.cu
- test/CMakeLists.txt
Also refines some of the checks to make sure that the underlying libraries are never called for unsupported cases
> Add SpMM tests

- docs_input/api/linalg/matvec/matvec.rst
- docs_input/basics/sparse_tensor.rst
- include/matx/operators/matvec.h
- include/matx/transforms/matmul/matvec_cusparse.h
- test/00_sparse/Matvec.cu
- test/CMakeLists.txt
> Add SpMV support for matvec transformation

- include/matx/core/make_sparse_tensor.h
- include/matx/transforms/convert/dense2sparse_cusparse.h
- include/matx/transforms/matmul/matmul_cusparse.h
Also fixes a few minor details related to zero-size allocation and host-side modification of device memory.
> Support mixed-precision for SpMM

- include/matx/transforms/matmul/matmul_cuda.h
- test/00_transform/MatMul.cu
For better perf on rank 4 batched matmuls.
> Change rank limit for batching

- include/matx/core/sparse_tensor_format.h
Rationale:
more consistent with order in which they appear in level spec
> changed order of level exp / format in the file

- include/matx/core/sparse_tensor_format.h
(1) use uppercase template vars
(2) use cuda::std in case we want to run on device (3) make print level private
(3) fixed typo in Expr (was expr in two branches)
(4) more short-cuts for readability
> various stylistic changes to sparse tensor format file

- include/matx/generators/linspace.h
> Fix rank of linspace

- docs_input/api/stats/avgvar/stdd.rst
- include/matx/operators/stdd.h
- include/matx/transforms/reduce.h
- test/00_operators/ReductionTests.cu
- test/test_vectors/generators/00_operators.py
> Add ddof parameter to stdd

- docs_input/api/linalg/other/normalize.rst
- include/matx/operators/normalize.h
- include/matx/operators/operators.h
- include/matx/transforms/normalize.h
- test/00_transform/Norm.cu
- test/test_vectors/generators/00_transforms.py
> Add Normalize function

- docs_input/api/searchsort/argsort.rst
- include/matx/core/iterator.h
- include/matx/operators/argsort.h
- include/matx/operators/operators.h
- include/matx/transforms/cub.h
- test/00_tensor/CUBTests.cu
> add argsort operator

- include/matx/core/cache.h
- include/matx/transforms/fft/fft_cuda.h
Currently when an FFT is executed in a stream both the FFT plan and the workspace require memory. The plan uses memory for the twiddle factors, and the workspace is temporary memory used while the FFT is executing. If an application launches many FFTs this memory usage can grow significantly. 
However, if the memory is always used in the same stream, it is never accessed at the same time and is wasted. For this PR we are changing the cache manager to track workspace memory per stream, and FFTs will look up the pointer each time they run an FFT. If an FFT requiring more memory is launched in the same stream, the cache will free and re-allocate a larger block of memory. The twiddle factors can also use a noticeable amount of memory, and again they are wasted by creating many plans for the …
> Reduce FFT Memory Usage

- include/matx/transforms/cub.h
This simplifies `OptimizedExecSort` to work across multiple dimensions without batching, using the same approach as in #956.
> simplify OptimizedExecSort

- include/matx/operators/interp.h
- test/00_operators/interp_test.cu
Was mentioned in #926, but not part of #936.
> interp1: add support for higher dimensional sample points and values

- docs_input/basics/sparse_tensor.rst
- include/matx/core/make_sparse_tensor.h
- include/matx/core/sparse_tensor.h
Also updates doc, and reforms code with more rigid style
> Introduce DIA format factory method

- cmake/GetGTest.cmake
Updating google test for new gcc/clang version compatibility
> Updating Google Test

- include/matx/core/allocator.h
Closes https://github.com/NVIDIA/MatX/issues/1007
> Allocate pinned host memory instead of managed when managed isn't available

- include/matx/core/pybind.h
- test/00_transform/MatMul.cu
> Support ND operators and transforms to/from python
